SELECT GS.CATEGORY, GS.APPLICATION AS "SRC", GS.VALUE AS "SRC_VL", GT.APPLICATION AS "TGT", GT.VALUE AS "TGT_VL"
FROM MAESTRO.TBL_TRANS_GLOBAL_SOURCE GS, MAESTRO.TBL_TRANS_GLOBAL_TARGET GT
WHERE GS.XCO_ID = GT.XCO_ID
AND GS.CATEGORY = ?
