# --- Pool3G Daily report processing ---
eai.report.valo.pool3g.daily.input.dir=/serveur_apps/EAIReports/input/VALO_POOL3G/
eai.report.valo.pool3g.daily.dollaru.ressource.name=RL_SFDH_VALO_POOL3G_J
eai.report.valo.pool3g.daily.input.dir.archives.subdir=/serveur_apps/EAIReports/input/VALO_POOL3G/archives
eai.report.valo.pool3g.daily.input.dir.errors.subdir=/serveur_apps/EAIReports/input/VALO_POOL3G/errors
eai.report.valo.pool3g.daily.input.delay.ms=60000
eai.report.valo.pool3g.daily.input.file.pattern=^Valo_Pool3G_J_.*\\.csv$
eai.report.valo.pool3g.daily.output.dir=/serveur_apps/EAIReports/output/VALO_POOL3G/
eai.report.valo.pool3g.daily.input.file.extension=.csv
