# --- Pool3G Daily report processing ---
eai.report.valo.pool3g.daily.input.dir=/serveur_apps/EAIReports/input/VALO_POOL3G/
eai.report.valo.pool3g.daily.dollaru.ressource.name=RL_SFDH_VALO_POOL3G_J
eai.report.valo.pool3g.daily.input.dir.archives.subdir=/serveur_apps/EAIReports/input/VALO_POOL3G/archives
eai.report.valo.pool3g.daily.input.dir.errors.subdir=/serveur_apps/EAIReports/input/VALO_POOL3G/errors
eai.report.valo.pool3g.daily.input.delay.ms=60000
eai.report.valo.pool3g.daily.input.file.pattern=^Valo_Pool3G_J_.*\\.csv$
eai.report.valo.pool3g.daily.output.dir=/serveur_apps/EAIReports/output/VALO_POOL3G/
eai.report.valo.pool3g.daily.input.file.extension=.csv

# --- ACADIA report processing ---
eai.report.acadia.prepare.input.cso.dir=/serveur_apps/EAIReports/input/ACADIA/
eai.report.acadia.prepare.input.cso.file.pattern=^CSO_Report_.*\\.txt$
eai.report.acadia.prepare.input.ice.dir=/serveur_apps/EAIReports/input/ACADIA/
eai.report.acadia.prepare.input.ice.file.pattern=^.*\\.txt$
eai.report.acadia.prepare.dollaru.ressource.name=RL_SFDH_ACADIA
eai.report.acadia.prepare.input.dir.archives.subdir=/serveur_apps/EAIReports/input/ACADIA/archives
eai.report.acadia.prepare.input.dir.errors.subdir=/serveur_apps/EAIReports/input/ACADIA/errors
eai.report.acadia.prepare.input.delay.ms=60000
eai.report.acadia.prepare.input.ice.encoding=ASCII
eai.report.acadia.prepare.output.dir=/serveur_apps/EAIReports/output/ACADIA/
eai.report.acadia.prepare.output.file.extension=.ready
