{
 "title": "EAI Apache Camel (no-kube)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(camel_exchanges_total,job)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(camel_exchanges_total{job=~\"${job}\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(camel_exchanges_total{job=~\"${job}\",camelContext=\"$context\"},routeId)"
    }
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": {
     "query": "label_values(camel_message_history_seconds_count{job=~\"${job}\",camelContext=\"$context\",routeId=~\"$route\"},nodeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Routes Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(camel_routes_running_routes{job=~\"$job\",camelContext=\"$context\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "100 * sum(camel_routes_running_routes{job=~\"$job\",camelContext=\"$context\"}) / sum(camel_routes_added_routes{job=~\"$job\",camelContext=\"$context\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "max(camel_routes_added_routes{job=~\"$job\",camelContext=\"$context\"})",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context in the time range",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(camel_exchanges_inflight{job=~\"$job\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 * sum(increase(camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\"}[$__range])) / sum(increase(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Camel Context Overview - RED Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Rate : Executions / sec",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (irate(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Duration : Avg Execution time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (increase(camel_route_policy_seconds_sum{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) / sum by (routeId) (increase(camel_route_policy_seconds_count{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors : Failure Rates",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (increase(camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) / sum by (routeId) (increase(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  { "title": "Traffic Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Ex/sec",
   "type": "stat",
   "description": "Show the numbers of exchanges per second for camel route $route",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 19 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}