{
 "title": "EAI Apache Camel",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\"},job)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\",job=~\"${job}\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(camel_exchanges_succeeded_total{job=~\"${job}\",camelContext=\"$context\"},routeId)"
    }
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": {
     "query": "label_values(camel_message_history_seconds_count{job=~\"${job}\",camelContext=\"$context\",routeId=~\"$route\"},nodeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Routes Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  camel_routes_running_routes{\n    job=~\"$job\",\n    camelContext=\"$context\"\n  }\n)",
     "legendFormat": "Instances"
    },
    {
     "expr": "sum(\n  camel_routes_running_routes{\n    job=~\"$job\",\n    camelContext=\"$context\"\n  }\n)\n/\nsum(\n  camel_routes_added_routes{\n    job=~\"$job\",\n    camelContext=\"$context\"\n  }\n)\n* 100",
     "legendFormat": "Running"
    },
    {
     "expr": "max(\n  camel_routes_added_routes{\n    job=~\"$job\",\n    camelContext=\"$context\"\n  }\n)",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context in the time range",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    camel_exchanges_total{job=~\"$job\",camelContext=\"$context\"}[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n  increase(\n    camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\"}[$__range]\n  )\n)"
    },
    {
     "expr": "sum by (camelContext) (\n  increase(\n    camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\"}[$__range]\n  )\n)\n/\nsum by (camelContext) (\n  increase(\n    camel_exchanges_total{job=~\"$job\",camelContext=\"$context\"}[$__range]\n  )\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation : CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(process_cpu_usage{job=~\"$job\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Saturation : Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\",area=\"heap\"}) / sum(jvm_memory_max_bytes{job=~\"$job\",area=\"heap\"})",
     "legendFormat": "heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\",area=\"nonheap\"}) / sum(jvm_memory_max_bytes{job=~\"$job\",area=\"nonheap\"})",
     "legendFormat": "nonheap"
    }
   ]
  },
  {
   "title": "Summary (non-k8s)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "count(camel_routes_running_routes{job=~\"$job\",camelContext=\"$context\"})"
    },
    {
     "expr": "sum(process_cpu_usage{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(camel_exchanges_inflight{job=~\"$job\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Camel Context Overview - RED Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Rate : Executions / sec",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n  irate(\n    camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]\n  )\n)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Duration : Avg Execution time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n  increase(camel_route_policy_seconds_sum{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)\n/\nsum by (routeId) (\n  increase(camel_route_policy_seconds_count{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Errors : Failure Rates",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n  increase(camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)\n/\nsum by (routeId) (\n  increase(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  { "title": "Traffic Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Ex/sec",
   "type": "stat",
   "description": "Show the numbers of exchanges per second for camel route $route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 22 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  irate(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 22 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n  irate(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - per instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 22 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  irate(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "$route Failure % - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 22 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n  increase(camel_exchanges_failed_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)\n/\nsum by (routeId) (\n  increase(camel_exchanges_total{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "stat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 22 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(camel_exchanges_inflight{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"})"
    }
   ]
  },
  { "title": "Execution Times Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Avg Exec time $route",
   "type": "stat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 38 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n  increase(camel_route_policy_seconds_sum{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)\n/\nsum by (camelContext) (\n  increase(camel_route_policy_seconds_count{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 38 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n  increase(camel_route_policy_seconds_sum{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)\n/\nsum by (camelContext) (\n  increase(camel_route_policy_seconds_count{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 38 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n  increase(camel_route_policy_seconds_sum{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)\n/\nsum by (instance) (\n  increase(camel_route_policy_seconds_count{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Processor Execution Times - $route",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "repeat": "route",
   "targets": [
    {
     "expr": "sum by (routeId,nodeId) (\n  increase(camel_message_history_seconds_sum{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\",nodeId=~\"$processor\"}[$__range])\n)\n/\nsum by (routeId,nodeId) (\n  increase(camel_message_history_seconds_count{job=~\"$job\",camelContext=\"$context\",routeId=~\"$route\",nodeId=~\"$processor\"}[$__range])\n)"
    }
   ]
  }
 ]
}