  CREATE TABLE "MAESTRO"."TBL_REFIT_DECELARATION_MONITORING" 
   (	"TECHNICAL_ID" NUMBER NOT NULL ENABLE, 
	"CALYPSO_MSG_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"CALYPSO_DECLARATION" CLOB, 
	"REFIT_FILE_NAME" VARCHAR2(64 CHAR), 
	"DECLARATION_TIMESTAMP" TIMESTAMP (2), 
	"REFIT_FILE_TYPE" VARCHAR2(10 CHAR), 
	"REFIT_STATUS" VARCHAR2(32 CHAR), 
	"LAST_UPDATE_DATE" TIMESTAMP (2), 
	"REFIT_RESPONSE_RECEPTION_TIMESTAMP" TIMESTAMP (2), 
	"REFIT_RESULT_FILE_ID" VARCHAR2(64 CHAR), 
	"REFIT_RESPONSE" CLOB, 
	"SENT_TO_CALYPSO" NUMBER(1,0), 
	"UNQTXIDR" VARCHAR2(128 CHAR), 
	"EVENTTYPE" VARCHAR2(8 CHAR), 
	"MESSAGE_TYPE" VARCHAR2(12 CHAR), 
	"TARGET_PLATFORM" VARCHAR2(12 CHAR), 
	"PRODUCT_TYPE" VARCHAR2(32 CHAR), 
	 CONSTRAINT "REFIT_DECLARATION_MANAGEMENT_PK" PRIMARY KEY ("TECHNICAL_ID"))
	 
	 


  CREATE TABLE "MAESTRO"."TBL_REFIT_DECELARATION_MONITORING_ARCHIVE" 
   (	"TECHNICAL_ID" NUMBER NOT NULL ENABLE, 
	"CALYPSO_MSG_ID" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"CALYPSO_DECLARATION" CLOB, 
	"REFIT_FILE_NAME" VARCHAR2(64 CHAR), 
	"DECLARATION_TIMESTAMP" TIMESTAMP (2), 
	"REFIT_FILE_TYPE" VARCHAR2(10 CHAR), 
	"REFIT_STATUS" VARCHAR2(32 CHAR), 
	"LAST_UPDATE_DATE" TIMESTAMP (2), 
	"REFIT_RESPONSE_RECEPTION_TIMESTAMP" TIMESTAMP (2), 
	"REFIT_RESULT_FILE_ID" VARCHAR2(64 CHAR), 
	"REFIT_RESPONSE" CLOB, 
	"SENT_TO_CALYPSO" NUMBER(1,0), 
	 CONSTRAINT "REFIT_DECLARATION_MANAGEMENT_ARCHIVE_PK" PRIMARY KEY ("TECHNICAL_ID"))
